'use strict'

const mongoose = require('mongoose')

const userSchema = mongoose.Schema({
	provider: String, // The provider with which the user authenticated (facebook, twitter, etc.).
	providerId: String, // A unique identifier for the user, as generated by the service provider.
	displayName: String, // The name of this user, suitable for display.
	firstName: String,
	lastName: String,
	email: String,
	phone: String,
})

// create model using the schema
const UserModel = mongoose.model('Users', userSchema)

// make available
module.exports = UserModel
