name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGO_DB_CONNECTION: ${{ secrets.MONGO_DB_CONNECTION }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      VERIFICATION_PORTAL_FACEBOOK_APP_ID: ${{ secrets.VERIFICATION_PORTAL_FACEBOOK_APP_ID }}
      VERIFICATION_PORTAL_FACEBOOK_APP_SECRET: ${{ secrets.VERIFICATION_PORTAL_FACEBOOK_APP_SECRET }}
      VERIFICATION_PORTAL_GOOGLE_MAPS_KEY: ${{ secrets.VERIFICATION_PORTAL_GOOGLE_MAPS_KEY }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2

      - run: yarn --frozen-lockfile
      - run: yarn lint
      - run: yarn test
        env:
          CI: true
